[DEFAULT]
# tt_um_essen_jtag
project = tt_um_essen

start_in_reset = no

# JTAG tests, controlled by probe
mode = ASIC_MANUAL_INPUTS

log_level = DEBUG

rp_clock_frequency = 200e6
clock_frequency = 50e6

